// <auto-generated />
using System;
using CleanCrud.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanCrud.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20211227053254_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CleanCrud.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformanceRate")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("money");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6379bb0a-c89f-4fd6-82c9-4df0c011a9f4"),
                            Name = "Muahmmed",
                            PerformanceRate = 95,
                            Salary = 50000m,
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = new Guid("8c821f20-f791-4a84-86d5-a0a4c2611cf0"),
                            Name = "Ahmed",
                            PerformanceRate = 96,
                            Salary = 70000m,
                            Specialization = "Surgery"
                        },
                        new
                        {
                            Id = new Guid("2f059a80-63ad-4482-b95d-0891071977dd"),
                            Name = "Yasmeen",
                            PerformanceRate = 92,
                            Salary = 80000m,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("e0556d41-c189-4779-b96f-3971a34d1ba4"),
                            Name = "Salma",
                            PerformanceRate = 97,
                            Salary = 85000m,
                            Specialization = "Pathology"
                        },
                        new
                        {
                            Id = new Guid("dea6b27e-1b75-452b-ae3b-0577b81e5c43"),
                            Name = "Esam",
                            PerformanceRate = 92,
                            Salary = 77000m,
                            Specialization = "Obstetrics"
                        },
                        new
                        {
                            Id = new Guid("6f9eeb2f-03e2-4532-9012-e89293450733"),
                            Name = "Maha",
                            PerformanceRate = 99,
                            Salary = 100000m,
                            Specialization = "Neurosurgery"
                        },
                        new
                        {
                            Id = new Guid("55dba7b8-b6f6-45e8-9169-474202fc919d"),
                            Name = "Khalid",
                            PerformanceRate = 91,
                            Salary = 97000m,
                            Specialization = "Radiology"
                        });
                });

            modelBuilder.Entity("CleanCrud.Models.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("43e9bce9-cc30-4cc7-8c12-3271baa25bc3"),
                            Name = "Cold"
                        },
                        new
                        {
                            Id = new Guid("e30c5a30-f25a-4ec8-a970-4cf50fd9d551"),
                            Name = "Stress"
                        },
                        new
                        {
                            Id = new Guid("fd0f093e-b170-48da-9d6a-d733d77a8ac9"),
                            Name = "Headache"
                        });
                });

            modelBuilder.Entity("CleanCrud.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b70424-53e3-4370-ae7d-f5c63263d81f"),
                            Name = "John"
                        },
                        new
                        {
                            Id = new Guid("14d1eeb9-edb5-41f3-a12a-8120e3d291fc"),
                            Name = "James"
                        },
                        new
                        {
                            Id = new Guid("b6f8f164-9915-4f74-9817-e1169d4272ac"),
                            Name = "Anderson"
                        });
                });

            modelBuilder.Entity("IssuePatient", b =>
                {
                    b.Property<Guid>("IssuesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IssuesId", "PatientsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("IssuePatient");
                });

            modelBuilder.Entity("IssuePatient", b =>
                {
                    b.HasOne("CleanCrud.Models.Issue", null)
                        .WithMany()
                        .HasForeignKey("IssuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CleanCrud.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
